// <auto-generated />
namespace NotifyControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_02));
        
        string IMigrationMetadata.Id
        {
            get { return "202106281850512_update_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
